name: cost_per_use
description: Track cost per use of your purchases.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^4.0.0
  sqflite: ^2.3.2
  path: ^1.8.3
  fl_chart: ^0.66.2
  intl: ^0.19.0

flutter:
  uses-material-design: true
